### ISSUE TITLE
Fails with python 3.*

### ISSUE THREAD

**Issue by mcepl** [mcepl/bayeux#2]
```
matej@wycliff: bayeux (master %)$ python3 setup.py test
running test
Checking .pth file support in .
/usr/bin/python3 -E -c pass
Searching for yamlish
Reading http://pypi.python.org/simple/yamlish/
Best match: yamlish 0.11
Downloading https://pypi.python.org/packages/source/y/yamlish/yamlish-0.11.tar.gz#md5=3cce34b8ddac3d37ed196831e6575935
Processing yamlish-0.11.tar.gz
Writing /tmp/easy_install-z7u9n0/yamlish-0.11/setup.cfg
Running yamlish-0.11/setup.py -q bdist_egg --dist-dir /tmp/easy_install-z7u9n0/yamlish-0.11/egg-dist-tmp-_bjoy9
zip_safe flag not set; analyzing archive contents...

Installed /home/matej/archiv/2012/RedHat/projekty/bayeux/yamlish-0.11-py3.3.egg
running egg_info
writing top-level names to bayeux.egg-info/top_level.txt
writing bayeux.egg-info/PKG-INFO
writing dependency_links to bayeux.egg-info/dependency_links.txt
writing requirements to bayeux.egg-info/requires.txt
reading manifest file 'bayeux.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'bayeux.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 36, in <module>
    install_requires=requires_list,
  File "/usr/lib64/python3.3/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.3/distutils/dist.py", line 929, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.3/distutils/dist.py", line 948, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.3/site-packages/setuptools/command/test.py", line 137, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/usr/lib/python3.3/site-packages/setuptools/command/test.py", line 117, in with_project_on_sys_path
    func()
  File "/usr/lib/python3.3/site-packages/setuptools/command/test.py", line 146, in run_tests
    testLoader = loader_class()
  File "/usr/lib64/python3.3/unittest/main.py", line 124, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python3.3/unittest/main.py", line 168, in parseArgs
    self.createTests()
  File "/usr/lib64/python3.3/unittest/main.py", line 175, in createTests
    self.module)
  File "/usr/lib64/python3.3/unittest/loader.py", line 137, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python3.3/unittest/loader.py", line 137, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python3.3/unittest/loader.py", line 96, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "/home/matej/archiv/2012/RedHat/projekty/bayeux/test/test_tap.py", line 11, in <module>
    import tap
  File "/home/matej/archiv/2012/RedHat/projekty/bayeux/tap.py", line 21, in <module>
    import yamlish
  File "/home/matej/archiv/2012/RedHat/projekty/bayeux/yamlish-0.11-py3.3.egg/yamlish.py", line 159, in <module>
    yaml.add_representer(unicode, str_representer_compact_multiline,
NameError: name 'unicode' is not defined
matej@wycliff: bayeux (master %)$
```

**Comment by mcepl** [comment]
Actually, this is not a correct bug (that one is in yamlish, and it has been fixed). However, bayeux truly doesn't work with py3k.

**Comment by mcepl** [comment]
Duplicate of #1
